# Base image
FROM python:3.10

# Set working directory inside the container
WORKDIR /app

# Copy dependency file
COPY requirements.txt .

# Install dependencies
RUN pip install -r requirements.txt

# Copy the rest of the project
COPY . .

# Command to run the app
CMD ["python"]